# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: file.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='file.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\nfile.proto\"!\n\x0f\x46ileDownloadRsp\x12\x0e\n\x06\x62uffer\x18\x01 \x01(\x0c\"\x1f\n\x0f\x46ileDownloadReq\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1f\n\rFileUploadReq\x12\x0e\n\x06\x62uffer\x18\x01 \x01(\x0c\"\x1f\n\rFileUploadRsp\x12\x0e\n\x06result\x18\x01 \x01(\t\"\t\n\x07ListReq\"0\n\x0e\x46ileSetNameReq\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08\x66ilesize\x18\x02 \x01(\x03\"\x10\n\x0e\x46ileSetNameRsp\"%\n\x07ListRsp\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04size\x18\x02 \x01(\x03\x32i\n\x04\x46ile\x12\x33\n\ruploadSetName\x12\x0f.FileSetNameReq\x1a\x0f.FileSetNameRsp\"\x00\x12,\n\x06upload\x12\x0e.FileUploadReq\x1a\x0e.FileUploadRsp\"\x00(\x01\x62\x06proto3'
)




_FILEDOWNLOADRSP = _descriptor.Descriptor(
  name='FileDownloadRsp',
  full_name='FileDownloadRsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='buffer', full_name='FileDownloadRsp.buffer', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=47,
)


_FILEDOWNLOADREQ = _descriptor.Descriptor(
  name='FileDownloadReq',
  full_name='FileDownloadReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='FileDownloadReq.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=80,
)


_FILEUPLOADREQ = _descriptor.Descriptor(
  name='FileUploadReq',
  full_name='FileUploadReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='buffer', full_name='FileUploadReq.buffer', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=82,
  serialized_end=113,
)


_FILEUPLOADRSP = _descriptor.Descriptor(
  name='FileUploadRsp',
  full_name='FileUploadRsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='FileUploadRsp.result', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=115,
  serialized_end=146,
)


_LISTREQ = _descriptor.Descriptor(
  name='ListReq',
  full_name='ListReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=148,
  serialized_end=157,
)


_FILESETNAMEREQ = _descriptor.Descriptor(
  name='FileSetNameReq',
  full_name='FileSetNameReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='FileSetNameReq.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='filesize', full_name='FileSetNameReq.filesize', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=159,
  serialized_end=207,
)


_FILESETNAMERSP = _descriptor.Descriptor(
  name='FileSetNameRsp',
  full_name='FileSetNameRsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=209,
  serialized_end=225,
)


_LISTRSP = _descriptor.Descriptor(
  name='ListRsp',
  full_name='ListRsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='ListRsp.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='size', full_name='ListRsp.size', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=227,
  serialized_end=264,
)

DESCRIPTOR.message_types_by_name['FileDownloadRsp'] = _FILEDOWNLOADRSP
DESCRIPTOR.message_types_by_name['FileDownloadReq'] = _FILEDOWNLOADREQ
DESCRIPTOR.message_types_by_name['FileUploadReq'] = _FILEUPLOADREQ
DESCRIPTOR.message_types_by_name['FileUploadRsp'] = _FILEUPLOADRSP
DESCRIPTOR.message_types_by_name['ListReq'] = _LISTREQ
DESCRIPTOR.message_types_by_name['FileSetNameReq'] = _FILESETNAMEREQ
DESCRIPTOR.message_types_by_name['FileSetNameRsp'] = _FILESETNAMERSP
DESCRIPTOR.message_types_by_name['ListRsp'] = _LISTRSP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FileDownloadRsp = _reflection.GeneratedProtocolMessageType('FileDownloadRsp', (_message.Message,), {
  'DESCRIPTOR' : _FILEDOWNLOADRSP,
  '__module__' : 'file_pb2'
  # @@protoc_insertion_point(class_scope:FileDownloadRsp)
  })
_sym_db.RegisterMessage(FileDownloadRsp)

FileDownloadReq = _reflection.GeneratedProtocolMessageType('FileDownloadReq', (_message.Message,), {
  'DESCRIPTOR' : _FILEDOWNLOADREQ,
  '__module__' : 'file_pb2'
  # @@protoc_insertion_point(class_scope:FileDownloadReq)
  })
_sym_db.RegisterMessage(FileDownloadReq)

FileUploadReq = _reflection.GeneratedProtocolMessageType('FileUploadReq', (_message.Message,), {
  'DESCRIPTOR' : _FILEUPLOADREQ,
  '__module__' : 'file_pb2'
  # @@protoc_insertion_point(class_scope:FileUploadReq)
  })
_sym_db.RegisterMessage(FileUploadReq)

FileUploadRsp = _reflection.GeneratedProtocolMessageType('FileUploadRsp', (_message.Message,), {
  'DESCRIPTOR' : _FILEUPLOADRSP,
  '__module__' : 'file_pb2'
  # @@protoc_insertion_point(class_scope:FileUploadRsp)
  })
_sym_db.RegisterMessage(FileUploadRsp)

ListReq = _reflection.GeneratedProtocolMessageType('ListReq', (_message.Message,), {
  'DESCRIPTOR' : _LISTREQ,
  '__module__' : 'file_pb2'
  # @@protoc_insertion_point(class_scope:ListReq)
  })
_sym_db.RegisterMessage(ListReq)

FileSetNameReq = _reflection.GeneratedProtocolMessageType('FileSetNameReq', (_message.Message,), {
  'DESCRIPTOR' : _FILESETNAMEREQ,
  '__module__' : 'file_pb2'
  # @@protoc_insertion_point(class_scope:FileSetNameReq)
  })
_sym_db.RegisterMessage(FileSetNameReq)

FileSetNameRsp = _reflection.GeneratedProtocolMessageType('FileSetNameRsp', (_message.Message,), {
  'DESCRIPTOR' : _FILESETNAMERSP,
  '__module__' : 'file_pb2'
  # @@protoc_insertion_point(class_scope:FileSetNameRsp)
  })
_sym_db.RegisterMessage(FileSetNameRsp)

ListRsp = _reflection.GeneratedProtocolMessageType('ListRsp', (_message.Message,), {
  'DESCRIPTOR' : _LISTRSP,
  '__module__' : 'file_pb2'
  # @@protoc_insertion_point(class_scope:ListRsp)
  })
_sym_db.RegisterMessage(ListRsp)



_FILE = _descriptor.ServiceDescriptor(
  name='File',
  full_name='File',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=266,
  serialized_end=371,
  methods=[
  _descriptor.MethodDescriptor(
    name='uploadSetName',
    full_name='File.uploadSetName',
    index=0,
    containing_service=None,
    input_type=_FILESETNAMEREQ,
    output_type=_FILESETNAMERSP,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='upload',
    full_name='File.upload',
    index=1,
    containing_service=None,
    input_type=_FILEUPLOADREQ,
    output_type=_FILEUPLOADRSP,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_FILE)

DESCRIPTOR.services_by_name['File'] = _FILE

# @@protoc_insertion_point(module_scope)
